### PR TITLE
Add a portable library

### PR DESCRIPTION
**Pull request by BenjaminChambers**
For those situations where it would be necessary.

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
Sorry for the late reply -- did not see this until now :).

I actually have a prototype of a portable lib as well. It is very similar to this, except that it used links to build the sources instead of duplicating the code.

**Comment by AlexGhiondea** [comment]
I think this would solve issue #9.

**Comment by BenjaminChambers** [comment]
Avoiding code duplication is always a good thing!

**Comment by AlexGhiondea** [comment]
Agreed! Let me know if you want to take that on (ie. creating the links) -- it should be straight forward to add the links (they can be done in bulk if you edit the csproj directly). If not, I will try to find the branch I had the changes done and push it. 

The reason why I hadn't yet done that is because I am not sure how to create the NuGet package that would expose them. I have a rough idea of how to do it though -- just need to sit down and do it :)

**Comment by AlexGhiondea** [comment]
Hey @BenjaminChambers -- I finally got around to pushing the change to add a portable library to the project -- would you mind taking a look?

**Comment by BenjaminChambers** [comment]
Actually, I've been dusting off some old code I worked on a while back, and I'm putting together a much more complete Sudoku package if you'd like to take a look at it.

It seems a bit more higher-level than what you've got here, so it might not interest you, but here it is:
https://github.com/BenjaminChambers/SudokuSharp

**Comment by AlexGhiondea** [comment]
Thanks! It looks like the one you have is geared more towards providing an actual gaming platform, right?

**Comment by AlexGhiondea** [comment]
Hey -- I am going to close this as I have a different approach for this.

**Pull request closed without merging**
